"""Fix user-quiz many-to-many relationship

Revision ID: 387fe9961f2f
Revises: 4b64d2e3fe16
Create Date: 2025-12-05 21:41:54.608108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387fe9961f2f'
down_revision: Union[str, Sequence[str], None] = '4b64d2e3fe16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
