"""Updtaed all tables

Revision ID: 3e17dd68ba2d
Revises: 7fc35becd622
Create Date: 2025-10-16 16:52:49.462587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e17dd68ba2d'
down_revision: Union[str, Sequence[str], None] = '7fc35becd622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('total_questions', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('estimated_time_minutes', sa.Integer(), nullable=True))
    op.alter_column('quizzes', 'questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_foreign_key(None, 'quizzes', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.alter_column('quizzes', 'questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('quizzes', 'estimated_time_minutes')
    op.drop_column('quizzes', 'total_questions')
    op.drop_column('quizzes', 'lesson_id')
    # ### end Alembic commands ###
